### ISSUE TITLE
Highlight scroll position in the Navbar

### ISSUE THREAD

**Issue by jossdoe** [jossdoe/cookbook#1]
When the user scrolls to a certain element, it should be reflected in the navigation bar by highlighting the item that correlates to that section.

Example: When you scroll to the 'Dolce' recipes, the 'Dolce' item in the navigation should be highlighted.

Docs: [How to do it with Bootstrap](https://getbootstrap.com/docs/4.5/components/scrollspy/#usage)

**Comment by BDeLucca** [comment]
I will do this
