### ISSUE TITLE
Do research for new ideas on the cookbook

### ISSUE THREAD

**Issue by Usamoto** [jossdoe/cookbook#22]
Search for ideas for the cookbook, if there are any details who might look great on the website.

**Comment by Usamoto** [comment]
**Research results:**

- We could add a section where someone can subscribe for a newsletter or get a free e-book for ancient Rome recipes.

- A list with all recipes.

- An about section.

**Comment by jossdoe** [comment]
Nice ideas! Should we add them all as seperate Issues to work on them?

**Comment by Usamoto** [comment]
> 
> 
> Nice ideas! Should we add them all as separate Issues to work on them?

Yes that would be nice.

**Comment by jossdoe** [comment]
Added the ideas as issues to the repo 👍
