### ISSUE TITLE
Add smooth scrolling to page

### ISSUE THREAD

**Issue by jossdoe** [jossdoe/cookbook#3]
We could add smooth scrolling behaviour to the page, so when clicking on an item in the navigation, the page won't just suddenly jump to that section, but show the user how it goes there.

Link: [Smooth Scrolling on CSS-Tricks](https://css-tricks.com/snippets/jquery/smooth-scrolling/)

**Comment by BDeLucca** [comment]
done it. accidentaly pushed to the master, but is this line that I changed.

<html lang="en" **style="scroll-behavior: smooth;"**>

Seems that it work pretty nice.
