### ISSUE TITLE
Smaller hovering icons in the images when they are smaller 

### ISSUE THREAD

**Issue by BDeLucca** [jossdoe/cookbook#34]
When the screen is smaller, the detail icons in the images (showed when hovering) should be smaller too.

**Comment by jossdoe** [comment]
There is also a bug in there:
```html
<i class="fas fa-clock solid"> 15 min</i>
<br />
<i class="fas fa-smile solid"> Easy</i>
<br />
<i class="fas fa-fire-alt solid"> Calories</i>
```
This doesn't show the correct font-family for the label text on the page. The labels actually need to be outside of the `<i>`-tags, like this:
```html
<i class="fas fa-clock solid"></i> 15 min
<br />
<i class="fas fa-smile solid"></i> Easy
<br />
<i class="fas fa-fire-alt solid"></i> Calories
```

**Comment by BDeLucca** [comment]
ok! Thanks! didn't realized that
