### ISSUE TITLE
Add hover animation (Assignment Level 3)

### ISSUE THREAD

**Issue by jossdoe** [jossdoe/cookbook#5]
In the assignment, it says for Level 3:

> When the user hovers the recipe image with the mouse, the recipe title must be displayed on top of it

Since the recipe title is already displayed in the headline directly above the image, maybe we could do something else for the hover-state. Maybe just scale up the image a little bit, so it pops into the foreground with a little bounce animation. We can do that with pure CSS.

**Comment by BDeLucca** [comment]
Working on it :D

**Comment by jossdoe** [comment]
This could be combined with Issue #2 – showing the additional info in an overlay on top of the image, for example. We could even use Icons to visualize it better, something like FontAwesome.
