### ISSUE TITLE
Issue images

### ISSUE THREAD

**Issue by BDeLucca** [jossdoe/cookbook#7]
Add Images of the food to the website. Molto Buono!

**Comment by Usamoto** [comment]
![priSpag](https://user-images.githubusercontent.com/46085749/86285005-2b343200-bbe4-11ea-807c-3ab5d154a8bb.jpg)
![secBran](https://user-images.githubusercontent.com/46085749/86285010-2d968c00-bbe4-11ea-8ce1-519df539b7a6.jpg)
![secFil](https://user-images.githubusercontent.com/46085749/86285023-34bd9a00-bbe4-11ea-9236-3c85ca723ef7.jpg)
![secMil](https://user-images.githubusercontent.com/46085749/86285027-36875d80-bbe4-11ea-80d3-d255b5fa1b3b.jpg)
![antiMoz](https://user-images.githubusercontent.com/46085749/86285032-37b88a80-bbe4-11ea-88d7-8af99a753880.jpg)
![antiVit](https://user-images.githubusercontent.com/46085749/86285034-38512100-bbe4-11ea-962d-4889c8f8b506.jpg)
![dolcCotta](https://user-images.githubusercontent.com/46085749/86285035-38e9b780-bbe4-11ea-8e1b-7f872104fe9e.jpg)
![dolcsem](https://user-images.githubusercontent.com/46085749/86285042-3a1ae480-bbe4-11ea-9223-237bcd2b4ad9.jpg)
![dolcTirami](https://user-images.githubusercontent.com/46085749/86285045-3ab37b00-bbe4-11ea-8c82-377a0efd0361.jpg)
![primRisso](https://user-images.githubusercontent.com/46085749/86285047-3be4a800-bbe4-11ea-9aa3-f420250a0a83.jpg)
![primTag](https://user-images.githubusercontent.com/46085749/86285048-3c7d3e80-bbe4-11ea-8b3e-8213979f89d4.jpg)
![antiProci](https://user-images.githubusercontent.com/46085749/86285684-5cf9c880-bbe5-11ea-848e-274a35ee9b85.jpg)

**Comment by Usamoto** [comment]
In the 1st attempt, I downloaded some unnecessary pictures which don't fit for our project, and through a better suggestion from Bruno I found more appropriate pictures. The search was extended through the 1:1 and that there were some pictures with low resolution, which I saw after I downloaded and opened them.

**Comment by Usamoto** [comment]
Put the pictures into the code.

**Comment by Usamoto** [comment]
commit: b4468c
